apiVersion: v1
kind: Service
metadata:
  name: bobosales-svc
  labels:
    app: bobosales
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  - port: 443
    protocol: TCP
    name: https
    targetPort: 443
  selector:
    app: bobosales
