apiVersion: v1
kind: ReplicationController
metadata:
  name: bobosales-rc
  labels:
    name: bobosales
    version: 1.2.7.16
spec:
  replicas: 1
  selector:
    app: bobosales
    version: 1.2.7.16
  template:
    metadata:
      labels:
        app: bobosales
        version: 1.2.7.16
    spec:
      volumes:
        - name: bobosales-uploads
          awsElasticBlockStore:
            volumeID: vol-3db938cb
            fsType: ext4
      imagePullSecrets:
        - name: docker-registry-key
      containers:
      - name: bobosales
        image: bobosales/bobosales:1.2.7.16
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 15
        env:
          - name: DEBUG
            value: "1"
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /app/public/uploads
            name: bobosales-uploads
      - name: bobosales-cron
        image: bobosales/bobosales:1.2.7.16
        command:
          - "./cron.sh"
        env:
          - name: DEBUG
            value: "0"
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
