apiVersion: v1
kind: ReplicationController
metadata:
  name: ksl-rc
  labels:
    name: ksl
    version: 1.2.19.23
spec:
  replicas: 1
  selector:
    app: ksl
    version: 1.2.19.23
  template:
    metadata:
      labels:
        app: ksl
        version: 1.2.19.23
    spec:
      volumes:
        - name: ksl-uploads
          awsElasticBlockStore:
            volumeID: vol-f233bd04
            fsType: ext4
      imagePullSecrets:
        - name: docker-registry-key
      containers:
      - name: ksl
        image: bobosales/ksl:1.2.19.23
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 15
        env:
          - name: DEBUG
            value: "0"
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /app/public/uploads
            name: ksl-uploads
      - name: ksl-cron
        image: bobosales/ksl:1.2.19.23
        command:
          - "./cron.sh"
        env:
          - name: DEBUG
            value: "1"
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
