apiVersion: v1
kind: ReplicationController
metadata:
  name: testing-ksl-rc
  labels:
    name: testing-ksl
    version: 1.2.19.19
spec:
  replicas: 1
  selector:
    app: testing-ksl
    version: 1.2.19.19
  template:
    metadata:
      labels:
        app: testing-ksl
        version: 1.2.19.19
    spec:
      volumes:
        - name: testing-ksl-uploads
          awsElasticBlockStore:
            volumeID: vol-7678e380
            fsType: ext4
      imagePullSecrets:
        - name: docker-registry-key
      containers:
      - name: testing-ksl
        image: bobosales/ksl:1.2.19.19
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 15
        env:
          - name: LARAVEL_ENV
            value: testing
          - name: DEBUG
            value: "1"
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - mountPath: /app/public/uploads
            name: testing-ksl-uploads
      - name: testing-ksl-cron
        image: bobosales/ksl:1.2.19.19
        command:
          - "./cron.sh"
        env:
          - name: DEBUG
            value: "1"
          - name: LARAVEL_ENV
            value: testing
          - name: DB_HOST
            value: REDACTED
          - name: DB_USER
            value: REDACTED
          - name: DB_PASS
            value: REDACTED
          - name: DB_NAME
            value: REDACTED
